version: '3.7'
services: 
    mongodb_container:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=test
        ports:
            - 27018:27017
        volumes:
            - './data/db'
    worker-service:
        image: "worker-service"
        container_name: worker-service
        build:
          context: .
          dockerfile: Integracao.Worker.Service/Dockerfile
        links:
            - "mongodb_container"          
volumes:
     mongodb_container: